[internal]
checkpoints = 'Internal/Checkpoints'
raw = 'Internal/Raw/CSV'

[internal.reference]
reference = 'Internal/Reference'
scimago = 'Internal/Reference/Scimago'
pdfs = 'Internal/Reference/PDFs'

[internal.manuscript]
figures = 'Internal/Manuscript/Figures'
tables = 'Internal/Manuscript/Tables'

[internal.intermediate]
csv = 'Internal/Intermediate/CSV'
graphs = 'Internal/Intermediate/Graphs'
models = 'Internal/Intermediate/Models'
embeddings = 'Internal/Intermediate/Embeddings'
classifier = 'Internal/Intermediate/Embeddings/Classifier'

[internal.intermediate.hdf5]
voyage = 'Internal/Intermediate/HDF5/VoyageAIEmbeddings'
neuro = 'Internal/Intermediate/HDF5/DomainEmbeddings'

[public]
csv = 'Public/Data/CSV'
graphs = 'Public/Data/Graphs'
hdf5 = 'Public/Data/HDF5/DomainEmbeddings'
